# Generated by Django 5.0.4 on 2024-05-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0002_studentassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherassessment',
            name='grade',
        ),
    ]
