# Generated by Django 5.0.4 on 2024-04-20 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Student",
            "0002_remove_studentuser_student_id_studentuser_department_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=15, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=30, null=True)),
                ("date_of_birth", models.DateField(default="", null=True)),
                ("department", models.CharField(default="", max_length=50, null=True)),
                ("major", models.CharField(default="", max_length=50, null=True)),
                ("enrollment_date", models.DateField(default="", null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="StudentUser",
        ),
    ]
