# Generated by Django 5.0.4 on 2024-04-20 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0003_student_delete_studentuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
