# Generated by Django 5.0.4 on 2024-04-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Databases", "0003_major_department"),
        ("Student", "0009_remove_student_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Databases.major",
            ),
        ),
    ]
