# Generated by Django 5.0.4 on 2024-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0012_rename_id_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Nam", "Nam"), ("Nữ", "Nữ")], max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(
                choices=[
                    ("Đang học", "Đang học"),
                    ("Tạm dừng học", "Tạm dừng học"),
                    ("Thôi học", "Thôi học"),
                    ("Tốt nghiệp", "Tốt nghiệp"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="type",
            field=models.CharField(
                choices=[("Cử nhân", "Cử nhân"), ("Thạc sĩ", "Thạc sĩ")],
                max_length=20,
                null=True,
            ),
        ),
    ]
