# Generated by Django 5.0.4 on 2024-05-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0013_student_gender_student_state_student_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hometown",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
