# Generated by Django 5.0.4 on 2024-05-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0014_student_hometown"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="Avatar/Student/"),
        ),
    ]
