# Generated by Django 5.0.4 on 2024-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0002_course_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="id_course",
            field=models.CharField(max_length=3, null=True),
        ),
    ]
