# Generated by Django 5.0.4 on 2024-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_course_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=None, null=True, upload_to='Course/course_file/'),
        ),
    ]
