# Generated by Django 5.0.4 on 2024-05-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_course_id_course'),
        ('Grade', '0002_remove_grade_teacher'),
        ('Student', '0011_alter_student_major'),
        ('Teacher', '0006_remove_teacher_degrees_degrees_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grade.grade')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
            options={
                'unique_together': {('course', 'student', 'teacher')},
            },
        ),
    ]
