# Generated by Django 5.0.4 on 2024-05-02 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0006_teacherassessment"),
        ("Course", "0008_alter_course_syllabus"),
    ]

    operations = []
