# Generated by Django 5.0.4 on 2024-05-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0009_merge_20240503_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAssessment',
        ),
    ]
