# Generated by Django 5.0.4 on 2024-05-03 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0010_delete_teacherassessment"),
        ("Course", "0010_remove_course_course_file_remove_course_description_and_more"),
    ]

    operations = []
