# Generated by Django 5.0.4 on 2024-05-02 15:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Course", "0005_alter_course_id_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Thứ Hai"),
                            ("TUE", "Thứ Ba"),
                            ("WED", "Thứ Tư"),
                            ("THU", "Thứ Năm"),
                            ("FRI", "Thứ Sáu"),
                            ("SAT", "Thứ Bảy"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField(default=datetime.time(7, 0))),
                ("end_time", models.TimeField(default=datetime.time(8, 0))),
                (
                    "subject_hours",
                    models.IntegerField(
                        choices=[(1, "1 tiết"), (2, "2 tiết")], default=1
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Course.course",
                    ),
                ),
            ],
        ),
    ]
