# Generated by Django 5.0.4 on 2024-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HourOfDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="day_of_week",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="subject_hours",
        ),
    ]
