# Generated by Django 5.0.4 on 2024-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0002_dayofweek_hourofday_remove_schedule_day_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hourofday",
            name="hour",
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name="ClassTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days", models.ManyToManyField(to="Schedule.dayofweek")),
                ("hours", models.ManyToManyField(to="Schedule.hourofday")),
            ],
        ),
    ]
