# Generated by Django 5.0.4 on 2024-05-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0005_alter_course_id_course"),
        ("Schedule", "0003_alter_hourofday_hour_classtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="days",
            field=models.ManyToManyField(to="Schedule.dayofweek"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="hours",
            field=models.ManyToManyField(to="Schedule.hourofday"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Course.course",
            ),
        ),
        migrations.DeleteModel(
            name="ClassTime",
        ),
    ]
