# Generated by Django 5.0.4 on 2024-05-02 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Schedule",
            "0004_schedule_days_schedule_hours_alter_schedule_course_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="days",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="hours",
        ),
        migrations.AddField(
            model_name="schedule",
            name="days",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedule.dayofweek",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="hours",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Schedule.hourofday",
            ),
        ),
    ]
