# Generated by Django 5.0.4 on 2024-05-02 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0005_remove_schedule_days_remove_schedule_hours_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="hours",
            new_name="start_hour",
        ),
    ]
