# Generated by Django 5.0.4 on 2024-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Schedule", "0006_rename_hours_schedule_start_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="end_hour",
            field=models.IntegerField(default=0),
        ),
    ]
