# Generated by Django 5.0.4 on 2024-05-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0010_remove_course_course_file_remove_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('syllabus', models.TextField(null=True)),
                ('course_file', models.FileField(blank=None, null=True, upload_to='Course/course_file/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
    ]
