# Generated by Django 5.0.4 on 2024-05-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_merge_20240503_1814'),
        ('File_document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='syllabus',
        ),
        migrations.AlterField(
            model_name='document',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Course.course'),
        ),
    ]
