# Generated by Django 5.0.4 on 2024-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_document', '0002_remove_document_syllabus_alter_document_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='syllabus',
            field=models.TextField(null=True),
        ),
    ]
