# Generated by Django 5.0.4 on 2024-05-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_document', '0003_document_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='syllabus',
        ),
    ]
