# Generated by Django 5.0.4 on 2024-04-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Databases", "0003_major_department"),
        ("Student", "0011_alter_student_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Student.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Databases.subject",
                    ),
                ),
            ],
        ),
    ]
