# Generated by Django 5.0.4 on 2024-04-29 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Databases", "0004_semester"),
        ("Registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationcourse",
            name="semester",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="Databases.semester",
            ),
            preserve_default=False,
        ),
    ]
