# Generated by Django 5.0.4 on 2024-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Databases", "0003_major_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester_id",
                    models.CharField(default="123", max_length=10, null=True),
                ),
            ],
        ),
    ]
