# Generated by Django 5.0.4 on 2024-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Databases", "0004_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="semester_id",
            field=models.CharField(default="", max_length=10, null=True),
        ),
    ]
