# Generated by Django 5.0.4 on 2024-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Databases", "0006_remove_semester_semester_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="semester_id",
            field=models.CharField(default="", max_length=10, null=True),
        ),
    ]
