# Generated by Django 5.0.4 on 2024-04-18 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0002_alter_studentuser_student_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="is_teacher",
        ),
    ]
