# Generated by Django 5.0.4 on 2024-04-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0003_remove_myuser_is_student_remove_myuser_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
