# Generated by Django 5.0.4 on 2024-04-18 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0004_myuser_is_student_myuser_is_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_student",
        ),
        migrations.RemoveField(
            model_name="myuser",
            name="is_teacher",
        ),
    ]
