# Generated by Django 5.0.4 on 2024-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0006_studentuser_date_of_birth_studentuser_major_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacheruser",
            name="myuser_ptr",
        ),
        migrations.AddField(
            model_name="myuser",
            name="GPA",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="myuser",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="myuser",
            name="faculty",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="myuser",
            name="sex",
            field=models.IntegerField(choices=[(0, "Nữ"), (1, "Nam")], default=0),
        ),
        migrations.DeleteModel(
            name="StudentUser",
        ),
        migrations.DeleteModel(
            name="TeacherUser",
        ),
    ]
