# Generated by Django 5.0.4 on 2024-04-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_remove_studentuser_student_id_and_more'),
        ('Login', '0007_studentuser_enrollment_date_teacheruser_department_and_more'),
    ]

    operations = [
    ]
