# Generated by Django 5.0.4 on 2024-04-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_merge_20240418_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='student_id',
            field=models.CharField(default='default_value', max_length=30),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='teacher_id',
            field=models.CharField(default='default_value', max_length=30),
        ),
    ]
