# Generated by Django 5.0.4 on 2024-04-19 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0009_studentuser_student_id_teacheruser_teacher_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacheruser",
            name="myuser_ptr",
        ),
        migrations.DeleteModel(
            name="StudentUser",
        ),
        migrations.DeleteModel(
            name="TeacherUser",
        ),
    ]
