# Generated by Django 5.0.4 on 2024-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0010_remove_teacheruser_myuser_ptr_delete_studentuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Admin", "Admin"),
                ],
                default="Student",
                max_length=20,
            ),
        ),
    ]
