# Generated by Django 5.0.4 on 2024-04-26 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Login", "0007_remove_teacheruser_myuser_ptr_myuser_gpa_myuser_age_and_more"),
        ("Login", "0011_alter_myuser_user_type"),
    ]

    operations = []
