# Generated by Django 5.0.4 on 2024-04-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('year_obtained', models.IntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degrees',
            field=models.ManyToManyField(blank=True, to='Teacher.degrees'),
        ),
    ]
