# Generated by Django 5.0.4 on 2024-05-03 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0006_remove_teacher_degrees_degrees_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="teaching_schedule",
        ),
    ]
