# Generated by Django 5.0.4 on 2024-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0007_remove_teacher_teaching_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="degrees",
            name="major",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="degrees",
            name="type",
            field=models.CharField(
                choices=[
                    ("Cử nhân", "Cử nhân"),
                    ("Thạc sĩ", "Thạc sĩ"),
                    ("Tiến sĩ", "Tiến sĩ"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                choices=[("Nam", "Nam"), ("Nữ", "Nữ")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="degrees",
            name="year_obtained",
            field=models.IntegerField(default=2010, null=True),
        ),
    ]
