# Generated by Django 5.0.4 on 2024-05-03 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0008_degrees_major_degrees_type_teacher_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="degrees",
            name="name",
        ),
    ]
