# Generated by Django 5.0.4 on 2024-05-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0009_remove_degrees_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
