# Generated by Django 5.0.4 on 2024-05-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Teacher", "0010_teacher_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="degrees",
            name="year_obtained",
            field=models.IntegerField(null=True),
        ),
    ]
