# Generated by Django 5.0.4 on 2024-05-01 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Grade", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="teacher",
        ),
    ]
